name: condominios_web
description: Version de CONDOMINIUM MC en web

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.7
  photo_view: ^0.13.0
  intl: ^0.17.0
  month_picker_dialog: ^0.4.0
  syncfusion_flutter_pdf: ^19.3.57-beta
  open_file: ^3.2.1
  path_provider: ^2.0.4
  universal_html: ^2.0.8
  widgets: ^1.4.5
  pdf: ^3.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/EstadodeCuenta.png
    - assets/avisos.png
    - assets/infousuario.png
    - assets/mensajes.png
    - assets/directorio.png
    - assets/documentos.png
    - assets/confirmacionadm.png
    - assets/nuevoanuncioadm.png
    - assets/logoo.png
    - assets/cerrar.png
    - assets/correcto.png
    - assets/punto.png
    - assets/nada.png
    - assets/comprobado.png
    - assets/pagado.png
    - assets/reloj.png
    - assets/servicios.png
    - assets/autolavado.png
    - assets/tintoreria.png
    - assets/NEGOCIOS.png
    - assets/RESERVACIONES.png
    - assets/BALANCE.png
    - assets/fondo.png
    - assets/gota-de-agua.png
    - assets/gotas.png
    - assets/ropa-sucia.png
    - assets/coche.png
    - assets/morosos.png
    - assets/retrasar.png
    - assets/NuevoPago.png
    - assets/informes.png